### ISSUE TITLE
[BUG] Generic git module parsing always expects a module path in the regexp

### ISSUE THREAD

**Issue by hofalk** [tdharris/vscode-terraform-link-docs#16]
Hi,

Love using your extension, great work!

We are using git repos as source quite a lot, but most repositories do not have a module path, so our sources look like this:
`git@github.com:owner/repo.git?ref=v1.2.3`

This is not matched and linked by the extension as the `?` quantifier only matches `ref` and `module` together.
In my testing a slight adjustment of the regexp seems to do the trick

https://github.com/tdharris/vscode-terraform-link-docs/blob/main/src/terraform/module.ts#L53

```diff
- const re = /^(git::|git::ssh:\/\/)?((.*@)?)(?<domain>[^:\/]+)(:|\/)(?<owner>[\w-]+)\/(?<repo>[\w-]+)(.git)?(\/\/(?<module>[\w-\/]+)(\?ref=(?<ref>[\w.-]+))?)?$/;
+ const re = /^(git::|git::ssh:\/\/)?((.*@)?)(?<domain>[^:\/]+)(:|\/)(?<owner>[\w-]+)\/(?<repo>[\w-]+)(.git)?(\/\/(?<module>[\w-\/]+))?(\?ref=(?<ref>[\w.-]+))?$/;
```

I ran it through different test cases on regex101.com and it seems to work fine:
https://regex101.com/r/c6lB7v/1

**Comment by tdharris** [comment]
Thanks, nice catch! Always helps to see everyone's examples and thank you for the regex validation effort. I've released as [v0.0.7](https://github.com/tdharris/vscode-terraform-link-docs/releases/tag/v0.0.7), publishing now, it should be available on the Marketplace soon.
