### ISSUE TITLE
Support for Zed editor?

### ISSUE THREAD

**Issue by Jeff-SearchPilot** [tdharris/vscode-terraform-link-docs#86]
Might be a bit of a long shot but are there any plans to port/re-write this extension for [Zed](https://zed.dev/)? It's pretty much the only thing I miss when working on tf code in Zed.

Either way - great project, thanks!

**Comment by tdharris** [comment]
Thanks! I'm keeping my eye on Zed for sure, I don't have any plans yet for a new extension there.
