### ISSUE TITLE
Wrong links for non-official providers

### ISSUE THREAD

**Issue by kristoflemmens** [tdharris/vscode-terraform-link-docs#94]
Hi,

Great extension, keep up the good work. I might have found an issue.

When I define a provider in the `required_providers` section it resolves an incorrect link for the providers that are not official.

```
terraform {
  required_version = "~> 1.9"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }

    azapi = {
      source  = "Azure/azapi"
      version = "~> 1.15"
    }
  }
}
```
![image](https://github.com/user-attachments/assets/7bfcda51-f45b-438f-82fe-f003bad5b7b9)

![image](https://github.com/user-attachments/assets/0ce3ef90-bc84-4fb5-ba25-7721167a2d3c)

**Comment by tdharris** [comment]
I took a closer look here and am fairly confident that the generated doc links you have shown above aren't from this extension.

To verify, I have attempted to duplicate and checked the extension logs:

1. In the vscode `Output` tab ( `Ctrl+Shift+U` or `View > Output` ), from the dropdown on the right, selecting `Terraform Link Docs`.

2. I created a new `main.tf` file and pasted the following contents:
    ```tf
    terraform {
        required_version = "~> 1.9"
      
        required_providers {
          azurerm = {
            source  = "hashicorp/azurerm"
            version = "~> 4.0"
          }
      
          azapi = {
            source  = "Azure/azapi"
            version = "~> 1.15"
          }
        }
    }
    
    resource "aws_s3_bucket" "example" {
      bucket = "my-bucket"
    }
    
    module "vpc" {
      source = "terraform-aws-modules/vpc/aws"
    }
    ```

    Here is the extension output channel log:
    ```console
    [terraform-link-docs] LMR {"type":"module","range":[{"line":5,"character":19},{"line":5,"character":36}],"moduleSource":"hashicorp/azurerm"}
    [terraform-link-docs] LMR {"type":"module","range":[{"line":10,"character":19},{"line":10,"character":30}],"moduleSource":"Azure/azapi"}
    [terraform-link-docs] LMR {"type":"resource","range":[{"line":16,"character":10},{"line":16,"character":23}],"dataOrResource":"resource","resourceType":"aws_s3_bucket"}
    [terraform-link-docs] LMR {"type":"module","range":[{"line":21,"character":12},{"line":21,"character":41}],"moduleSource":"terraform-aws-modules/vpc/aws"}
    [terraform-link-docs] resource link https://www.terraform.io/docs/providers/aws/r/s3_bucket
    [terraform-link-docs] module link https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws
    ```
    
    **Note** :
    - For every line that matches an initial filter, we'll see a `LMR` prefix. We see all 4 being picked up, but they haven't yet been processed.
    - After being processed, we'll see either a `resource link` or `module link` prefix in the output indicating the link that will be used. We only see 2 here and not from the providers. I took another peak in the code and I'm not handling any source values that contain a single `/` (providers). I _think_ I remember purposefully ignoring the provider case because I found that some other Extension (likely from Hashicorp) handled that use-case for me nicely already. Let us know if you identify the extension that is generating that.

**Comment by kristoflemmens** [comment]
Hi,

I did some extra tests. When I disable your extension I don't have any documentation links so I'm pretty sure it they are generated by your extension. I then recreated your test with the following code:
```
terraform {
  required_version = "~> 1.9"

  required_providers {
    azapi = {
      source  = "Azure/azapi"
      version = "~> 1.12"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

resource "azapi_resource_group" "rg" {
  name     = "example-resources"
  location = "East US"
}

resource "azurerm_resource_group" "rg" {
  name     = "example-resources"
  location = "East US"
}
```
This gave me the following extension output channel log:
```
[terraform-link-docs] LMR {"type":"module","range":[{"line":5,"character":17},{"line":5,"character":28}],"moduleSource":"Azure/azapi"}
[terraform-link-docs] LMR {"type":"module","range":[{"line":9,"character":17},{"line":9,"character":34}],"moduleSource":"hashicorp/azurerm"}
[terraform-link-docs] LMR {"type":"resource","range":[{"line":15,"character":10},{"line":15,"character":30}],"dataOrResource":"resource","resourceType":"azapi_resource_group"}
[terraform-link-docs] LMR {"type":"resource","range":[{"line":20,"character":10},{"line":20,"character":32}],"dataOrResource":"resource","resourceType":"azurerm_resource_group"}
[terraform-link-docs] resource link https://www.terraform.io/docs/providers/azapi/r/resource_group
[terraform-link-docs] resource link https://www.terraform.io/docs/providers/azurerm/r/resource_group
```
